### ISSUE TITLE
tests: fix util tests

### ISSUE THREAD

**Issue by examachine** [examachine/pisi#47]
$ tests/run.py util
* Running tests in utiltests
testCleanArTimestamp (utiltests.UtilTestCase) ... ok
testDirSize (utiltests.UtilTestCase) ... FAIL
testGetFileHashes (utiltests.UtilTestCase) ... FAIL
testRemovePathPrefix (utiltests.UtilTestCase) ... ok
testSubPath (utiltests.UtilTestCase) ... ok

======================================================================
FAIL: testDirSize (utiltests.UtilTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/utiltests.py", line 70, in testDirSize
    self.assertEqual(dir_size('tests/utilfiles/linktonowhere'), 23)
AssertionError: 0 != 23

======================================================================
FAIL: testGetFileHashes (utiltests.UtilTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/utiltests.py", line 79, in testGetFileHashes
    self.assertEqual(len([x for x in get_file_hashes('tests/utilfiles/')]), 4)
AssertionError: 3 != 4

----------------------------------------------------------------------
Ran 5 tests in 0.009s

FAILED (failures=2)

**Comment by examachine** [comment]
fixed in git
