### ISSUE TITLE
test: build broken

### ISSUE THREAD

**Issue by examachine** [examachine/pisi#82]
```
$ tests/run.py build
* Running tests in buildtests
testBasicBuild (buildtests.BuildTestCase) ... Destination directory /Volumes/Centauri/Users/malfunct/Code/projects/pisi/tmp does not exist. Creating it.
Writing current database version for dbversion
Writing current database version for filesdbversion
Building PISI source package: a
Compiling action script
Safety switch: the component system.devel cannot be found
Fetching source from: https://github.com/examachine/pisi/raw/master/tests/buildtests/merhaba-pisi-1.0.tar.bz2
merhaba-pisi-1.0.tar.bz2       (1.0 KB)100%     41.79 MB/s [00:00:00] [complete]
Source archive is stored: /Volumes/Centauri/Users/malfunct/Code/projects/pisi/tmp/var/cache/pisi/archives/merhaba-pisi-1.0.tar.bz2
Unpacking archive... unpacked (/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tmp/var/tmp/pisi/a-1.0-1/work)
Setting up source...
setup
Building source...
build
Installing...
install
actions.py: WorkDir = merhaba-pisi-1.0
ERROR
testBuildNumber (buildtests.BuildTestCase) ... Destination directory /Volumes/Centauri/Users/malfunct/Code/projects/pisi/tmp/var/tmp/pisi/a-1.0-1/work/merhaba-pisi-1.0/tmp does not exist. Creating it.
Writing current database version for dbversion
Writing current database version for filesdbversion
ERROR

======================================================================
ERROR: testBasicBuild (buildtests.BuildTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/buildtests.py", line 40, in testBasicBuild
    pb.build()
  File "./pisi/build.py", line 207, in build
    self.run_install_action()
  File "./pisi/build.py", line 343, in run_install_action
    self.run_action_function(ctx.const.install_func, True)
  File "./pisi/build.py", line 413, in run_action_function
    self.actionLocals[func]()
  File "error", line 19, in install
  File "./pisi/actionsapi/pisitools.py", line 174, in rename
    error(_('ActionsAPI [rename]: No such file or directory: %s') % (sourceFile))
  File "./pisi/actionsapi/__init__.py", line 27, in error
    raise Error(msg)
Error: ActionsAPI [rename]: No such file or directory: /Volumes/Centauri/Users/malfunct/Code/projects/pisi/tmp/var/tmp/pisi/a-1.0-1/install/usr/bin/merhaba-pisi.py

======================================================================
ERROR: testBuildNumber (buildtests.BuildTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/buildtests.py", line 44, in testBuildNumber
    self.testBasicBuild()
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/buildtests.py", line 37, in testBasicBuild
    shutil.copy('tests/buildtests/a/actions.py-1', 'tests/buildtests/a/actions.py')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'tests/buildtests/a/actions.py-1'

----------------------------------------------------------------------
Ran 2 tests in 15.944s

FAILED (errors=2)
```

**Comment by examachine** [comment]
ok, this was working. no idea why it's broken LOL

**Comment by examachine** [comment]
fixed in master
