### ISSUE TITLE
conflict test b0rkz

### ISSUE THREAD

**Issue by examachine** [examachine/pisi#83]
```
$ tests/run.py conflict
* Running tests in conflicttests
testConflictWithEachOther (conflicttests.ConflictTestCase) ... Destination directory /Volumes/Centauri/Users/malfunct/Code/projects/pisi/tmp does not exist. Creating it.
Writing current database version for dbversion
Writing current database version for filesdbversion
ERROR
testConflictWithEachOtherAndInstalled (conflicttests.ConflictTestCase) ... ERROR
testConflictWithInstalled (conflicttests.ConflictTestCase) ... ERROR

======================================================================
ERROR: testConflictWithEachOther (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/conflicttests.py", line 50, in setUp
    pkg = pisi.specfile.Package()
AttributeError: 'module' object has no attribute 'specfile'

======================================================================
ERROR: testConflictWithEachOtherAndInstalled (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/conflicttests.py", line 21, in setUp
    testcase.TestCase.setUp(self)
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/testcase.py", line 29, in setUp
    database = database, write = database)
  File "./pisi/api.py", line 107, in init
    ctx.filesdb = pisi.db.files.FilesDB()
  File "./pisi/db/files.py", line 21, in __init__
    shelve.LockedDBShelf.__init__(self, 'files')
  File "./pisi/db/lockeddbshelve.py", line 124, in __init__
    self.open(filename, dbname, filetype, flags, mode)
  File "./pisi/db/lockeddbshelve.py", line 155, in open
    self.lock()
  File "./pisi/db/lockeddbshelve.py", line 165, in lock
    raise Error(_("Another instance of PISI is running. Only one instance is allowed to modify the PISI database at a time."))
Error: Another instance of PISI is running. Only one instance is allowed to modify the PISI database at a time.

======================================================================
ERROR: testConflictWithInstalled (conflicttests.ConflictTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/conflicttests.py", line 21, in setUp
    testcase.TestCase.setUp(self)
  File "/Volumes/Centauri/Users/malfunct/Code/projects/pisi/tests/testcase.py", line 29, in setUp
    database = database, write = database)
  File "./pisi/api.py", line 107, in init
    ctx.filesdb = pisi.db.files.FilesDB()
  File "./pisi/db/files.py", line 21, in __init__
    shelve.LockedDBShelf.__init__(self, 'files')
  File "./pisi/db/lockeddbshelve.py", line 124, in __init__
    self.open(filename, dbname, filetype, flags, mode)
  File "./pisi/db/lockeddbshelve.py", line 155, in open
    self.lock()
  File "./pisi/db/lockeddbshelve.py", line 165, in lock
    raise Error(_("Another instance of PISI is running. Only one instance is allowed to modify the PISI database at a time."))
Error: Another instance of PISI is running. Only one instance is allowed to modify the PISI database at a time.

----------------------------------------------------------------------
Ran 3 tests in 6.834s

FAILED (errors=3)
Traceback (most recent call last):
  File "tests/run.py", line 51, in <module>
    run_test_suite(module.suite)
  File "tests/run.py", line 28, in run_test_suite
    pisi.api.finalize()
  File "./pisi/api.py", line 129, in finalize
    pisi.db.repo.finalize()
  File "./pisi/db/repo.py", line 126, in finalize
    db.close()
  File "./pisi/db/repo.py", line 52, in close
    self.d.close()
  File "./pisi/db/lockeddbshelve.py", line 170, in close
    self.db.close()
  File "/usr/local/lib/python2.7/site-packages/bsddb3/dbobj.py", line 138, in close
    return self._cobj.close(*args, **kwargs)
bsddb3.db.DBRunRecoveryError: (-30972, 'BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery -- BDB0060 PANIC: fatal region error detected; run recovery')
```

**Comment by examachine** [comment]
oh it should be caused by those silly ref errors easy

**Comment by examachine** [comment]
```*- mode: compilation; default-directory: "/Users/malfunct/Code/projects/pisi/" -*-
Compilation started at Wed Feb 22 05:36:46

tests/run.py conflict
* Running tests in conflicttests
testConflictWithEachOther (conflicttests.ConflictTestCase) ... ok
testConflictWithEachOtherAndInstalled (conflicttests.ConflictTestCase) ... ok
testConflictWithInstalled (conflicttests.ConflictTestCase) ... ok

----------------------------------------------------------------------
Ran 3 tests in 3.820s

OK

Compilation finished at Wed Feb 22 05:36:50
```
